title: Octavio Landa | Data Integrity & Analytics
description: Portafolio Profesional de Ciencia de Datos y Auditor√≠a de Sistemas.
theme: jekyll-theme-midnight
google_analytics: 
show_downloads: false